"""Part 1 diagnostic: probe every game for real input support.

Not a test — a measuring instrument. Run it to regenerate INPUT_MATRIX.md,
which is the evidence the fixes are driven from.

    python tests/diagnose_input.py

Method: EventTarget.addEventListener is instrumented before page scripts run
(see browser_util), so we can tell whether a synthesised keypress actually
invoked game code. Watching the DOM is not enough — a canvas game reacting to
ArrowLeft only mutates a JS variable.
"""

import os
import sys
import threading

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from baseline import DESKTOP, GAMES, MOBILE  # noqa: E402
from browser_util import (  # noqa: E402
    active_screen, browser_page, clickable_but_unfocusable, focusable_count,
    hits, listener_types, reset_hits, start_game,
)

KEYS = ['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown',
        'Enter', 'Space', '1', 'a']


def serve():
    import app
    from werkzeug.serving import make_server
    srv = make_server('127.0.0.1', 0, app.app, threaded=True)
    port = srv.socket.getsockname()[1]
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    return srv, f'http://127.0.0.1:{port}'


def probe(game, base, viewport, touch, browser=None):
    r = {'loads': False, 'starts': False, 'focusable': 0, 'kb_listener': False,
         'kb_fires': 0, 'tap_fires': 0, 'orphans': [], 'errors': []}
    try:
        with browser_page(viewport, base, game.file, touch=touch,
                          browser=browser) as (page, problems):
            r['loads'] = True

            started, before, after = start_game(page, game.start)
            # Canvas games have no .screen; treat "start control vanished or
            # a canvas became visible" as having entered play.
            entered = page.evaluate("""() => {
                const c = document.querySelector('canvas');
                return !!(c && c.offsetParent !== null);
            }""")
            r['starts'] = bool(started and (after != before or entered))

            types = listener_types(page)
            r['kb_listener'] = 'keydown' in types or 'keyup' in types
            r['focusable'] = focusable_count(page)
            r['orphans'] = sorted(clickable_but_unfocusable(page))[:4]

            reset_hits(page)
            for k in KEYS:
                try:
                    page.keyboard.press(k)
                except Exception:
                    pass
            page.wait_for_timeout(400)
            h = hits(page)
            r['kb_fires'] = h.get('keydown', 0) + h.get('keyup', 0)

            reset_hits(page)
            for sel in (game.tap, 'button:visible', 'canvas'):
                if not sel:
                    continue
                try:
                    el = page.query_selector(sel.replace(':visible', ''))
                    if el and el.is_visible():
                        el.click(timeout=2000)
                        break
                except Exception:
                    continue
            page.wait_for_timeout(300)
            h = hits(page)
            r['tap_fires'] = (h.get('click', 0) + h.get('pointerdown', 0)
                              + h.get('touchstart', 0))

            r['errors'] = [p for p in problems if 'pageerror' in p][:2]
    except Exception as e:
        r['errors'].append(f'probe crashed: {type(e).__name__}: {e}')
    return r


def main():
    from playwright.sync_api import sync_playwright
    srv, base = serve()
    rows = []
    pw = sync_playwright().start()
    shared = pw.chromium.launch()
    try:
        for g in GAMES:
            d = probe(g, base, DESKTOP, touch=False, browser=shared)
            m = probe(g, base, MOBILE, touch=True, browser=shared)
            rows.append((g, d, m))
            print(f'  probed {g.file}', flush=True)
    finally:
        shared.close()
        pw.stop()
        srv.shutdown()

    flag = lambda b: '✅' if b else '❌'  # noqa: E731
    out = [
        '# Input Matrix',
        '',
        'Generated by `python tests/diagnose_input.py`.',
        '',
        'Measured by instrumenting `addEventListener` before page scripts run, so',
        '"keydown fired" means game code actually ran — not that the DOM happened',
        'to change. Desktop = 1280x800, Mobile = 390x844 with touch enabled.',
        '',
        '| Game | Loads | Starts | Focusable | Has keydown | Keydown fired | Tap fired (mobile) | Unfocusable click targets |',
        '|---|---|---|---|---|---|---|---|',
    ]
    for g, d, m in rows:
        out.append(
            f'| `{g.file}` | {flag(d["loads"])} | {flag(d["starts"])} | '
            f'{d["focusable"]} | {flag(d["kb_listener"])} | {d["kb_fires"]} | '
            f'{m["tap_fires"]} | {", ".join(d["orphans"]) or "—"} |'
        )

    out += ['', '## Reading this', '',
            '- **Has keydown / Keydown fired = ❌/0** — the game cannot be played by',
            '  keyboard at all. A kid on a desktop must use the mouse.',
            '- **Unfocusable click targets** — elements wired for click that Tab can',
            '  never reach, so they are invisible to keyboard and screen readers.',
            '', '## Errors seen', '']
    any_err = False
    for g, d, m in rows:
        for e in d['errors'] + m['errors']:
            out.append(f'- `{g.file}`: {e}')
            any_err = True
    if not any_err:
        out.append('None — every game loads clean.')

    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'INPUT_MATRIX.md')
    open(path, 'w').write('\n'.join(out) + '\n')
    print(f'\nwrote {path}\n')
    print('\n'.join(out[8:]))


if __name__ == '__main__':
    main()
